
site_name: dc-options
theme:
  name: null
nav:
  - Home: index.md
  - Usage: usage.md
  - API: api.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
